name: pt_flutter_clean_architecture_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Data Store
  shared_preferences: ^2.0.9
  # Localization
  easy_localization: ^3.0.0
  # Screen Util
  flutter_screenutil: ^5.0.1
  # Clean Architecture
  pt_flutter_architecture:
    git:
      url: https://github.com/tien-px/pt_flutter_architecture

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/animations/
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic